<?php
namespace gamboamartin\importador\models;
use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class imp_destino extends _modelo_parent{

    public function __construct(PDO $link){
        $tabla = 'imp_destino';
        $columnas = array($tabla=>false,'imp_origen'=>$tabla,'imp_database'=>$tabla,'imp_server'=>'imp_database',
            'adm_seccion'=>'imp_origen','adm_namespace'=>'adm_seccion');
        $campos_obligatorios[] = 'descripcion';
        $campos_obligatorios[] = 'descripcion_select';
        $campos_obligatorios[] = 'imp_origen_id';
        $campos_obligatorios[] = 'imp_database_id';
        $campos_obligatorios[] = 'fecha_ultima_ejecucion';


        $columnas_extra['imp_destino_id_ultimo'] = "IFNULL((SELECT imp_ultimo.id_ultimo FROM imp_ultimo WHERE imp_ultimo.imp_destino_id = imp_destino.id),0)";


        $tipo_campos = array();


        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, tipo_campos: $tipo_campos);

        $this->NAMESPACE = __NAMESPACE__;
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if(!isset($this->registro['descripcion'])){
            $registro = $this->descripcion(id: -1, registro: $this->registro);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error asignar descripcion', data: $registro);
            }
            $this->registro = $registro;
        }
        if(!isset($this->registro['ultimo_id_origen'])){
            $this->registro['ultimo_id_origen'] = 0;
        }
        if(!isset($this->registro['fecha_ultima_ejecucion'])){
            $this->registro['fecha_ultima_ejecucion'] = date('Y-m-d H:i:s');
        }
        $r_alta_bd = parent::alta_bd(keys_integra_ds: $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta', data: $r_alta_bd);
        }
        return $r_alta_bd;
    }

    public function alta_full(int $imp_destino_id){

        $imp_destino = $this->registro(registro_id: $imp_destino_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener destino',data:  $imp_destino);
        }

        $ejecuciones = (new _inserciones())->aplica_inserciones(imp_destino: $imp_destino,link: $this->link, usuario_id: $this->usuario_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar registros',data:  $ejecuciones);
        }

        $r_imp_destino = (new imp_ultimo(link: $this->link))->ejecuta_ultimo(id_ultimo: $ejecuciones->ultimo_id_origen,
            imp_destino_id: $this->registro_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar destino',data:  $r_imp_destino);
        }

        $ejecuciones->r_imp_destino = $r_imp_destino;

        return $ejecuciones;
    }

    private function data_descripcion(int $imp_destino_id, array $registro){
        $foraneas = $this->foraneas(imp_destino_id: $imp_destino_id, registro: $registro);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al obtener foraneas', data: $foraneas);
        }

        $imp_origen = (new imp_origen(link: $this->link))->registro(registro_id: $foraneas->imp_origen_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener imp_origen', data: $imp_origen);
        }
        $imp_database = (new imp_database(link: $this->link))->registro(registro_id: $foraneas->imp_database_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener imp_database', data: $imp_database);
        }
        $foraneas->imp_origen = $imp_origen;
        $foraneas->imp_database = $imp_database;

        return $foraneas;
    }

    /**
     * Inicializa datos de foraneas
     * @param array $registro Registro en proceso
     * @return stdClass
     */
    private function data_foraneas(array $registro): stdClass
    {
        $existen_foraneas = true;
        $imp_database_id = -1;
        $imp_origen_id = -1;

        if(!isset($registro['imp_origen_id'])|| !isset($registro['imp_database_id'])){
            $existen_foraneas = false;
        }
        if(isset($registro['imp_origen_id'])){
            $imp_origen_id = $registro['imp_origen_id'];
        }
        if(isset($registro['imp_database_id'])){
            $imp_database_id = $registro['imp_database_id'];
        }

        $data = new stdClass();
        $data->existen_foraneas = $existen_foraneas;
        $data->imp_database_id = $imp_database_id;
        $data->imp_origen_id = $imp_origen_id;
        return $data;
    }

    /**
     * Integra la descripcion en un registro en proceso de alta o modifica
     * @param int $id Identificador de la entidad
     * @param array $registro Registro en proceso
     * @return array
     */
    private function descripcion(int $id, array $registro): array
    {
        $descripcion = $this->genera_descripcion(imp_destino_id: $id,registro:  $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener descripcion', data: $descripcion);
        }
        $registro['descripcion'] = $descripcion;
        return $registro;
    }

    private function descripcion_string(stdClass $data): string
    {
        $descripcion = $data->imp_origen['imp_server_ip'].' '.$data->imp_origen['imp_database_descripcion'];
        $descripcion .= ' '.$data->imp_origen['adm_seccion_descripcion'];
        $descripcion .= ' '.$data->imp_database['imp_database_descripcion'].' '.$data->imp_database['imp_server_ip'];
        $descripcion .= ' '.$data->imp_database['imp_server_domain'];
        return $descripcion;
    }

    private function foraneas(int $imp_destino_id, array $registro){
        $foraneas = $this->data_foraneas(registro: $registro);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al obtener foraneas', data: $foraneas);
        }

        if(!$foraneas->existen_foraneas) {
            $foraneas = $this->foraneas_previas(foraneas: $foraneas,imp_destino_id:  $imp_destino_id);
            if (errores::$error) {
                return $this->error->error(mensaje: 'Error al obtener foraneas', data: $foraneas);
            }
        }
        return $foraneas;
    }

    private function foraneas_previas(stdClass $foraneas, int $imp_destino_id){
        $registro_previo = $this->registro(registro_id: $imp_destino_id);
        if (errores::$error) {
            return $this->error->error(mensaje: 'Error al obtener registro_previo', data: $registro_previo);
        }

        if (!isset($registro['imp_origen_id'])) {
            $foraneas->imp_origen_id = $registro_previo['imp_origen_id'];
        }
        if (!isset($registro['imp_database_id'])) {
            $foraneas->imp_database_id = $registro_previo['imp_database_id'];
        }
        return $foraneas;
    }

    private function genera_descripcion(int $imp_destino_id, array $registro){
        $data = $this->data_descripcion(imp_destino_id: $imp_destino_id,registro:  $registro);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener data', data: $data);
        }
        $descripcion = $this->descripcion_string(data: $data);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener descripcion', data: $descripcion);
        }
        return $descripcion;
    }



    public function inserta_ultimos(int $imp_destino_id){

        $imp_destino = $this->registro(registro_id: $imp_destino_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener destino',data:  $imp_destino);
        }


        $ejecuciones = (new _inserciones())->aplica_inserciones_ultimas(imp_destino: $imp_destino,link: $this->link,
            usuario_id: $this->usuario_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar registros',data:  $ejecuciones);
        }

        $r_imp_destino = (new imp_ultimo(link: $this->link))->ejecuta_ultimo(id_ultimo: $ejecuciones->ultimo_id_origen,
            imp_destino_id: $this->registro_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar destino',data:  $r_imp_destino);
        }

        $ejecuciones->r_imp_destino = $r_imp_destino;

        return $ejecuciones;
    }

    public function inserta_ultimos_id(int $imp_destino_id){

        $imp_destino = $this->registro(registro_id: $imp_destino_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener destino',data:  $imp_destino);
        }


        $ejecuciones = (new _inserciones())->aplica_inserciones_ultimas_id(imp_destino: $imp_destino,link: $this->link,
            usuario_id: $this->usuario_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al insertar registros',data:  $ejecuciones);
        }

        $r_imp_destino = (new imp_ultimo(link: $this->link))->ejecuta_ultimo(id_ultimo: $ejecuciones->ultimo_id_origen,
            imp_destino_id: $this->registro_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar destino',data:  $r_imp_destino);
        }

        $ejecuciones->r_imp_destino = $r_imp_destino;

        return $ejecuciones;
    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false, array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {


        if(!isset($registro['descripcion'])){
            $registro = $this->descripcion(id: $this->registro_id, registro: $registro);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error asignar descripcion', data: $registro);
            }
        }


        $r_modifica_bd= parent::modifica_bd(registro: $registro, id: $id,reactiva:  $reactiva,keys_integra_ds:  $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar', data: $r_modifica_bd);
        }
        return $r_modifica_bd;

    }

    public function modifica_full(int $imp_destino_id){

        $imp_destino = $this->registro(registro_id: $imp_destino_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener destino',data:  $imp_destino);
        }

        $ejecuciones = (new _modificaciones())->aplica_modificaciones(imp_destino: $imp_destino,link: $this->link, usuario_id: $this->usuario_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar registros',data:  $ejecuciones);
        }

        $r_imp_destino = (new imp_ultimo(link: $this->link))->ejecuta_ultimo(id_ultimo: $ejecuciones->ultimo_id_origen, imp_destino_id: $this->registro_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar destino',data:  $r_imp_destino);
        }

        $ejecuciones->r_imp_destino = $r_imp_destino;

        return $ejecuciones;
    }

    public function modifica_ultimos(int $imp_destino_id){

        $imp_destino = $this->registro(registro_id: $imp_destino_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener destino',data:  $imp_destino);
        }

        $ejecuciones = (new _modificaciones())->aplica_modificaciones_ultimas_id(imp_destino: $imp_destino,link: $this->link, usuario_id: $this->usuario_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar registros',data:  $ejecuciones);
        }

        $r_imp_destino = (new imp_ultimo(link: $this->link))->ejecuta_ultimo(id_ultimo: $ejecuciones->ultimo_id_origen, imp_destino_id: $this->registro_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar destino',data:  $r_imp_destino);
        }

        $ejecuciones->r_imp_destino = $r_imp_destino;

        return $ejecuciones;
    }

    public function modifica_ultimos_id(int $imp_destino_id){

        $imp_destino = $this->registro(registro_id: $imp_destino_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener destino',data:  $imp_destino);
        }

        $ejecuciones = (new _modificaciones())->aplica_modificaciones_ultimas_id(imp_destino: $imp_destino,link: $this->link, usuario_id: $this->usuario_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar registros',data:  $ejecuciones);
        }

        $r_imp_destino = (new imp_ultimo(link: $this->link))->ejecuta_ultimo(id_ultimo: $ejecuciones->ultimo_id_origen, imp_destino_id: $this->registro_id);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar destino',data:  $r_imp_destino);
        }

        $ejecuciones->r_imp_destino = $r_imp_destino;

        return $ejecuciones;
    }



}