<?php
namespace gamboamartin\importador\models;
use base\orm\_modelo_parent;
use gamboamartin\errores\errores;
use PDO;
use stdClass;

class imp_database extends _modelo_parent{

    public function __construct(PDO $link){
        $tabla = 'imp_database';
        $columnas = array($tabla=>false,'imp_server'=>$tabla);
        $campos_obligatorios[] = 'descripcion';
        $campos_obligatorios[] = 'descripcion_select';
        $campos_obligatorios[] = 'imp_server_id';
        $campos_obligatorios[] = 'user';
        $campos_obligatorios[] = 'password';
        $campos_obligatorios[] = 'tipo';


        $columnas_extra['imp_database_n_origenes'] = /** @lang sql */
            "(SELECT COUNT(*) FROM imp_origen WHERE imp_origen.imp_database_id = imp_database.id)";

        $columnas_extra['imp_database_n_destinos'] = /** @lang sql */
            "(SELECT COUNT(*) FROM imp_destino WHERE imp_destino.imp_database_id = imp_database.id)";


        $tipo_campos = array();


        parent::__construct(link: $link, tabla: $tabla, campos_obligatorios: $campos_obligatorios,
            columnas: $columnas, columnas_extra: $columnas_extra, tipo_campos: $tipo_campos);

        $this->NAMESPACE = __NAMESPACE__;
    }

    public function alta_bd(array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if(!isset($this->registro['descripcion_select'])){
            $registro = $this->descripcion_select(registro: $this->registro);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error al obtener descripcion_select', data: $registro);
            }
            $this->registro = $registro;

        }
        $r_alta_bd = parent::alta_bd($keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al dar de alta', data: $r_alta_bd);
        }
        return $r_alta_bd;
    }

    /**
     * Integra la descripcion select de la entidad
     * @param array $registro Registro en proceso
     * @return array|string
     */
    private function descripcion_select(array $registro): array|string
    {
        $imp_server = (new imp_server(link: $this->link))->registro(registro_id: $registro['imp_server_id']);
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al obtener imp server', data: $imp_server);
        }

        $descripcion_select = $registro['descripcion'].' '.$imp_server['imp_server_domain'].' '.$imp_server['imp_server_ip'];

        $registro['descripcion_select'] = $descripcion_select;
        return $registro;
    }

    public function modifica_bd(array $registro, int $id, bool $reactiva = false, array $keys_integra_ds = array('codigo', 'descripcion')): array|stdClass
    {
        if(!isset($registro['descripcion_select'])){
            $registro = $this->descripcion_select(registro: $registro);
            if(errores::$error){
                return $this->error->error(mensaje: 'Error asignar descripcion', data: $registro);
            }
        }

        $r_modifica_bd= parent::modifica_bd(registro: $registro, id: $id,reactiva:  $reactiva,keys_integra_ds:  $keys_integra_ds); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error(mensaje: 'Error al modificar', data: $r_modifica_bd);
        }
        return $r_modifica_bd;

    }


}