<?php
/**
 * @author Martin Gamboa Vazquez
 * @version 1.0.0
 * @created 2022-05-14
 * @final En proceso
 *
 */
namespace gamboamartin\importador\controllers;

use base\controller\init;

use gamboamartin\errores\errores;
use gamboamartin\importador\html\imp_database_html;
use gamboamartin\importador\html\imp_server_html;
use gamboamartin\importador\models\imp_server;
use gamboamartin\system\_ctl_parent_sin_codigo;
use gamboamartin\system\links_menu;
use gamboamartin\template_1\html;
use PDO;
use stdClass;


class controlador_imp_server extends _ctl_parent_sin_codigo {

    public stdClass|array $imp_sever = array();
    private imp_server_html $html_local;

    public string $link_imp_database_alta_bd = '';


    public function __construct(PDO $link, html $html = new html(), stdClass $paths_conf = new stdClass()){
        $modelo = new imp_server(link: $link);

        $html_ = new imp_server_html(html: $html);
        $this->html_local = $html_;
        $obj_link = new links_menu(link: $link, registro_id: $this->registro_id);

        $datatables = new stdClass();
        $datatables->columns = array();
        $datatables->columns['imp_server_id']['titulo'] = 'Id';
        $datatables->columns['imp_server_descripcion']['titulo'] = 'Server';
        $datatables->columns['imp_server_ip']['titulo'] = 'IP';
        $datatables->columns['imp_server_proveedor']['titulo'] = 'Prov';
        $datatables->columns['imp_server_user']['titulo'] = 'User';
        $datatables->columns['imp_server_password']['titulo'] = 'Pass';
        $datatables->columns['imp_server_domain']['titulo'] = 'Domain';
        $datatables->columns['imp_server_n_databases']['titulo'] = 'N Databases';

        $datatables->filtro = array();
        $datatables->filtro[] = 'imp_server.id';
        $datatables->filtro[] = 'imp_server.descripcion';
        $datatables->filtro[] = 'imp_server.ip';
        $datatables->filtro[] = 'imp_server.proveedor';
        $datatables->filtro[] = 'imp_server.user';
        $datatables->filtro[] = 'imp_server.domain';

        parent::__construct(html: $html_, link: $link, modelo: $modelo, obj_link: $obj_link, datatables: $datatables,
            paths_conf: $paths_conf);

        $this->titulo_lista = 'Servidores';

        if(isset($this->registro_id) && $this->registro_id > 0){
            $imp_sever = (new imp_server($this->link))->registro(registro_id: $this->registro_id);
            if(errores::$error){
                $error = $this->errores->error(mensaje: 'Error al obtener imp_sever',data:  $imp_sever);
                print_r($error);
                exit;
            }
            $this->imp_sever = $imp_sever;
        }

        $link_imp_database_alta_bd = $this->obj_link->link_alta_bd(link: $link, seccion: 'imp_database');
        if(errores::$error){
            $error = $this->errores->error(mensaje: 'Error al obtener link',data:  $link_imp_database_alta_bd);
            print_r($error);
            exit;
        }
        $this->link_imp_database_alta_bd = $link_imp_database_alta_bd;


    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta =  parent::alta($header, $ws); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar template',data:  $r_alta, header: $header,ws: $ws);
        }

        $descripcion = $this->html_local->input_descripcion(cols: 6,row_upd: new stdClass(),value_vacio:  false,place_holder: 'Server');
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar input descripcion',data:  $descripcion, header: $header,ws: $ws);
        }
        $this->inputs->descripcion = $descripcion;

        return $r_alta;

    }

    /**
     * Integra los campos para vistas generales
     * @param array $inputs Inputs precargados
     * @return array
     */
    final protected function campos_view(array $inputs = array()): array
    {
        $keys = new stdClass();
        $keys->inputs = array('codigo','descripcion','ip','proveedor','user','password','domain');
        $keys->selects = array();

        $campos_view = (new init())->model_init_campos_template(
            campos_view: array(),keys:  $keys, link: $this->link);

        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializar campo view',data:  $campos_view);
        }

        return $campos_view;
    }

    public function databases(bool $header = true, bool $ws = false): array|stdClass|string
    {

        $data_view = new stdClass();
        $data_view->names = array('Id','Database', 'Server','IP','User','Password','Tipo','Acciones');
        $data_view->keys_data = array('imp_database_id','imp_database_descripcion','imp_server_descripcion','imp_server_ip','imp_database_user',
            'imp_database_password','imp_database_tipo');
        $data_view->key_actions = 'acciones';
        $data_view->namespace_model = 'gamboamartin\\importador\\models';
        $data_view->name_model_children = 'imp_database';


        $contenido_table = $this->contenido_children(data_view: $data_view, next_accion: __FUNCTION__, not_actions: $this->not_actions);
        if(errores::$error){
            return $this->retorno_error(
                mensaje: 'Error al obtener tbody',data:  $contenido_table, header: $header,ws:  $ws);
        }


        return $contenido_table;

    }




    protected function key_selects_txt(array $keys_selects): array
    {
        $keys_selects = (new \base\controller\init())->key_select_txt(cols: 6,key: 'codigo', keys_selects:$keys_selects, place_holder: 'Cod');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        $keys_selects = (new \base\controller\init())->key_select_txt(cols: 6,key: 'descripcion', keys_selects:$keys_selects, place_holder: 'Server');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        $keys_selects = (new \base\controller\init())->key_select_txt(cols: 6,key: 'ip', keys_selects:$keys_selects, place_holder: 'IP');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }
        $keys_selects = (new \base\controller\init())->key_select_txt(cols: 12,key: 'proveedor', keys_selects:$keys_selects, place_holder: 'Proveedor');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }
        $keys_selects = (new \base\controller\init())->key_select_txt(cols: 6,key: 'user', keys_selects:$keys_selects, place_holder: 'User');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }
        $keys_selects = (new \base\controller\init())->key_select_txt(cols: 6,key: 'password', keys_selects:$keys_selects, place_holder: 'Password');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }
        $keys_selects = (new \base\controller\init())->key_select_txt(cols: 12,key: 'domain', keys_selects:$keys_selects, place_holder: 'Domain');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al maquetar key_selects',data:  $keys_selects);
        }

        return $keys_selects;
    }

    protected function inputs_children(stdClass $registro): array|stdClass{
        $select_imp_server_id = (new imp_server_html(html: $this->html_base))->select_imp_server_id(
            cols:12,con_registros: true,id_selected:  $registro->imp_server_id,link:  $this->link, disabled: true);

        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener select_imp_server_id',data:  $select_imp_server_id);
        }


        $imp_database_descripcion = (new imp_database_html(html: $this->html_base))->input_descripcion(
            cols:6,row_upd:  new stdClass(), value_vacio: true, place_holder: 'Database');
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener imp_database_descripcion',
                data:  $imp_database_descripcion);
        }

        $imp_database_user = (new imp_database_html(html: $this->html_base))->input_text_required(
            cols: 6, disabled: false,name: 'user',place_holder: 'User',row_upd:   new stdClass(), value_vacio: false);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener imp_database_user',
                data:  $imp_database_user);
        }

        $imp_database_password = (new imp_database_html(html: $this->html_base))->input_text_required(
            cols: 6, disabled: false,name: 'password',place_holder: 'Password',row_upd:   new stdClass(), value_vacio: false);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener imp_database_password',
                data:  $imp_database_user);
        }

        $imp_database_tipo = (new imp_database_html(html: $this->html_base))->input_text_required(
            cols: 6, disabled: false,name: 'tipo',place_holder: 'Tipo',row_upd:   new stdClass(), value_vacio: false);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al obtener imp_database_tipo',
                data:  $imp_database_user);
        }


        $this->inputs = new stdClass();
        $this->inputs->imp_server_id = $select_imp_server_id;
        $this->inputs->imp_database_user = $imp_database_user;
        $this->inputs->imp_database_password = $imp_database_password;
        $this->inputs->imp_database_tipo = $imp_database_tipo;
        $this->inputs->imp_database_descripcion = $imp_database_descripcion;

        return $this->inputs;
    }



}
